apiVersion: apps/v1
kind: Deployment
metadata:
  name: test01
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: test01
  template:
    metadata:
      labels:
        app: test01
    spec:
      containers:
      - image: nginx
        name: test01
        ports:
        - containerPort: 80